# Generated by Django 5.0.14 on 2025-10-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0002_standardplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroPlates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='euro/')),
            ],
        ),
    ]
